### ISSUE TITLE
Corrupted Content on Firefox and Safari

### ISSUE THREAD

**Issue by kentfredric** [codebox/bitmeteros#53]
We did a fresh install, and firefox, upon visiting "localhost:2605" and getting the 303 response, fails with a "Corrupted Content" error.

```
HTTP/1.0 303 See Other
Location: http://localhost:2605\index.html
Server: BitMeterOS 0.8.0 Web Server
Date: Mon, 03 Dec 2012 23:56:06 +0000
Connection: Close
```

Chrome has no problem with this, but it would appear the problem is the direction of the slash in the location redirect.  Shouldn't that be `/` not `\` ? =) 

Manually going to  `http://localhost:2605/index.html`  , does of course, work fine.

A similar issue occurs on Safari, which produces a url of http://192.168.1.4:2605%5Cindex.html

**Comment by maphew** [comment]
This has reappeared in 0.8.0 Windows 7.
The workaround of adding `/index.html` is still effective.
