### ISSUE TITLE
BitMeter OS not Working on OS X (El Capitan)

### ISSUE THREAD

**Issue by LightMoon** [codebox/bitmeteros#68]
Hello

I encountered to "This package is incompatible with this version of OS X and may fail to install." error during the installation of both 0.7.6 and 0.8.0 versions.

Please let me know if there is a solution for this.

**Comment by codebox** [comment]
Did you try the 'El Capitan and later' installer available from here: http://codebox.org.uk/pages/bitmeteros/downloads

**Comment by LightMoon** [comment]
Yes, I tried the right version.

**Comment by LightMoon** [comment]
Any good news ?

**Comment by sfarzy** [comment]
Same here. Not working on El Capitan

**Comment by codebox** [comment]
Not sure what to do about this - I have 2 El Capitan systems and it installs and runs fine on both of them, I also know that other users have successfully installed it on that version of OSX - tricky...

**Comment by sfarzy** [comment]
This is what happened with me.
![Error 1](https://cloud.githubusercontent.com/assets/10276208/11601687/ca20631c-9afa-11e5-8c13-0a2cc2f68b32.png)

> Proceeded with "Install Anyway"

![Error 2](https://cloud.githubusercontent.com/assets/10276208/11601688/ca251b96-9afa-11e5-83ba-85e10f6a9c79.png)

**Comment by LightMoon** [comment]
Yes, this is exactly my problem too.
Is there anything we can do to help the debugging of process ?

**Comment by codebox** [comment]
Could someone try the latest installer for El Capitan from here please, this may all be my fault...

http://codebox.org.uk/pages/bitmeteros/downloads

**Comment by sfarzy** [comment]
@codebox Works like charm :+1:

**Comment by codebox** [comment]
I had deployed the wrong version of the installer to my site - sorry for the confusion

![images](https://cloud.githubusercontent.com/assets/615829/11607094/dabd9488-9b31-11e5-83f2-a4a4b7e8a657.jpg)
