### ISSUE TITLE
Request for monitoring & counting just Internet traffic

### ISSUE THREAD

**Issue by LightMoon** [codebox/bitmeteros#69]
It would be great if there was an option for monitoring and counting of just internet traffic.
Discriminating between LAN and Internet (WAN).

**Comment by harrisoftware** [comment]
yes please! its very hard to find an app that distinguishes between intranet and internet traffic. Whenever Time Machine runs, bandwidth monitoring numbers spike - and since its internal network traffic, it sure would be nice to be able to ignore this.

**Comment by codebox** [comment]
The 'pcap' branch contains code that will do this, available as precompiled binaries from here: http://codebox.org.uk/pages/bitmeteros/downloads - use the v0.8.0 installers. This version of the application is less stable that the main branch so be prepared for bugginess!
