### ISSUE TITLE
Web interface broken on OSX Sierra

### ISSUE THREAD

**Issue by codebox** [codebox/bitmeteros#71]
This seems to be due to a change in the sqlite3 library bundled with OSX Sierra, the bundled library is not 'fork-safe' meaning that if a forked process tries to use the library it will fail (the same issue is affecting many other applications including Python: https://bugs.python.org/issue27126 ). 

Since the BitMeter web-server component uses the fork() system call on OSX to allow multiple concurrent requests to be processed, this means that any request to the web interface that requires a database read/write will fail.

Note that the bmcapture component, and the command-line client bmclient are both unaffected, so BitMeter is still logging data but since most people use the web interface to read the data this is of limited use.

The best solution may be to bundle a different version of sqlite with BitMeter rather than using the system-supplied version,

**Comment by codebox** [comment]
resolved by adding latest sqlite3 source files into osx build and ignoring the O/S-supplied version of the library

**Comment by sfarzy** [comment]
Web interface in still broken on macOS Seirra. Used the latest version from product page.
![image](https://cloud.githubusercontent.com/assets/10276208/21642063/dab12c32-d2a5-11e6-81eb-b2f7373bbe23.png)
