### ISSUE TITLE
Tracking traffic for specific server

### ISSUE THREAD

**Issue by longtth** [codebox/bitmeteros#77]
How can I tracking upload/download traffic with specific server, like https://my.company.com/ ? 
If it's not implemented yet, can you consider to implement it?

**Comment by codebox** [comment]
BitMeterOS v0.8.0 can do this, although it isn't as stable as v0.7.x - see https://codebox.net/pages/bitmeteros/downloads

**Comment by longtth** [comment]
thank you very much @codebox
