### ISSUE TITLE
Does "bmdb webstop" only stop the web interface (or does it also stop bitmeter)

### ISSUE THREAD

**Issue by WiliTest** [codebox/bitmeteros#80]
Sorry to ask here, but the [forum link](https://forum.codebox.net/jforum/forums/list.page) is dead. Each time I start my computer bitmeter open a new brownser windows to show the webstop. I would like it works in the background. I saw in the [FAQ ](https://codebox.net/pages/bitmeteros/faq#weburl) I could stop/start the Web Interface, but it doesn't say if it will only stop the web interface or the whole app.

So does "bmdb webstop" only stop the web interface?

Thanks!

**Comment by codebox** [comment]
That command will only stop the web service, data will still be collected by the data capture service, however I don't think that is your problem. The web service should not open any browser windows, it is just a process that runs in the background and makes the BitMeter data available via a web interface if you want it. It sounds like you have a link to the BitMeter web page in the list of startup items that run when you turn on your computer/log in. Try Googling something like "change startup items for [your operating system name]" and see if that is the case.

**Comment by WiliTest** [comment]
Thanks a lot for your reply! Yes actually BitMeter was in the startup folder (I thought it needed to be there to run when the computer start.). So I understand it, I could remove it from the startup folder and BitMeter will still run each time the computer restart.

**Comment by codebox** [comment]
Yes, that's correct - glad you got it fixed
