### ISSUE TITLE
Possibility of tracking source/destination ports

### ISSUE THREAD

**Issue by Ziraya** [codebox/bitmeteros#85]
It would be very useful to be able to attribute network traffic to specific applications, especially on systems with limited transfer such as those using cellular modems, or servers hosted with metered connections. This could also help to reveal misconfiguration and infection.

Is information such as port bindings or port specific transfer statistics available to BitmeterOS?

**Comment by codebox** [comment]
There is something like this on the 0.8.0 branch (you can use pcap filters to monitor port/host specific traffic) but it needs a lot of work to make it robust and doesn't tie the traffic to specific applications, only to port numbers
