### ISSUE TITLE
⚠ it comes with malware (it installs an "anti-virus")

### ISSUE THREAD

**Issue by WiliTest** [codebox/bitmeteros#87]
I ended up with a bunch of suspicious .exe such as BitMeterWebService.exe  (known as Vuze, it also has the following name Avira Free Antivirus or or Gbp Service or ANIWConnService or Application Updater or BitMeter OS and it is developed by Vuze Inc. , it is also developed by Avira Operations GmbH & Co. KG Apple Inc. Spigot, Inc. Codebox Software).

**Comment by codebox** [comment]
I'm a little confused by your description, but I can assure you that BitMeter doesn't contain any malware of anti-virus software. Where did you download the installer from? Some sketchy download sites have been known to bundle their own installers in with the software that they are hosting - if in doubt download from the developer's website. Anyway, BitMeterWebService.exe is one of the components of BitMeter but it has nothing to do with Vuze or Avira or Apple Inc (?)
