### ISSUE TITLE
Release 0.8.0 on GitHub

### ISSUE THREAD

**Issue by scrouthtv** [codebox/bitmeteros#92]
There is a 0.8.0 (pre-) release on the codebox.net website:
![image](https://user-images.githubusercontent.com/23227405/90793767-5d246380-e30c-11ea-9643-1580100c4f9f.png)
However, this release is not tagged on GitHub. Where can I get it's source code?

Thanks in advance.

**Comment by codebox** [comment]
The source code for v0.8.0 is on the 'pcap' branch you can find it here: https://github.com/codebox/bitmeteros/tree/pcap
